---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
  endpoints:
  - port: https-metrics
    scheme: https
    interval: 10s
    path: /metrics/cadvisor
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
