#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: receiver
#  name: receiver
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: receiver
#  template:
#    metadata:
#      labels:
#        app: receiver
#    spec:
#      containers:
#      - name: receiver
#        image: thanos:latest
#        imagePullPolicy: Never
#        args:
#        - receive
#        - --label=receive_replica="0"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: receiver
#  labels:
#    app: receiver
#spec:
#  selector:
#    app: receiver
#  ports:
#  - name: grpc
#    port: 10901
#    targetPort: 10901
#  - name: http
#    port: 19291
#    targetPort: 19291