apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/fpetkovski/scratch/thanos-sharding/data
    containerPath: /data
  extraPortMappings:
  - containerPort: 30902
    hostPort: 30902
    protocol: TCP
  - containerPort: 30903
    hostPort: 30903
    protocol: TCP
  - containerPort: 30909
    hostPort: 30909
    protocol: TCP
